# Generated by Django 5.2.8 on 2025-11-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_remove_venta_cliente_nombre_venta_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Domiciliar'),
        ),
    ]
