# Generated by Django 5.2.8 on 2025-11-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_proveedor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('unidad', 'Unidad (Pza)'), ('metro', 'Metro (m)'), ('litro', 'Litro (L)'), ('galon', 'Galón (gal)'), ('libra', 'Libra (lb)'), ('kg', 'Kilogramo (kg)'), ('caja', 'Caja/Paquete')], default='unidad', max_length=20, verbose_name='Unidad de Medida'),
        ),
    ]
