# Generated by Django 5.2.8 on 2025-12-01 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_producto_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'verbose_name': 'Movimiento de Inventario', 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.AlterModelTable(
            name='movimiento',
            table='movimientos',
        ),
    ]
